/* MAXИГРА — persistent image cache using documented MAX DeviceStorage. */
(()=>{'use strict';
const ASSETS={play:'assets/кнопки/IMG_4614.jpeg',online:'assets/кнопки/IMG_4616.jpeg',profile:'assets/кнопки/IMG_4613.jpeg',leaderboard:'assets/кнопки/IMG_4609.jpeg',rules:'assets/кнопки/IMG_4612.jpeg',shop:'assets/кнопки/IMG_4605.jpeg',board_90s:'assets/boards/IMG_4486.jpeg',board_svo:'assets/boards/IMG_4487.jpeg',board_max:'assets/boards/IMG_4586.jpeg',board_orbita:'assets/boards/IMG_4587.jpeg',board_original:'assets/boards/IMG_4589.jpeg'};
const PREFIX='maxigra_asset_v1_';
const storage=window.WebApp?.DeviceStorage;
const memory=new Map();
const call=(method,key,value)=>{if(!storage?.[method])return Promise.resolve('');try{const p=value===undefined?storage[method](PREFIX+key):storage[method](PREFIX+key,value);return p&&typeof p.then==='function'?p.then(v=>String(v??'')):Promise.resolve(String(p??''));}catch{return Promise.resolve('')}};
async function fetchDataUrl(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('IMAGE_'+r.status);const blob=await r.blob();return await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||''));fr.onerror=reject;fr.readAsDataURL(blob)})}
function applyCss(){const root=document.documentElement;const map={play:'--mx-img-play',online:'--mx-img-online',profile:'--mx-img-profile',leaderboard:'--mx-img-leaderboard',rules:'--mx-img-rules',shop:'--mx-img-shop'};Object.entries(map).forEach(([k,v])=>{const x=memory.get(k);if(x)root.style.setProperty(v,'url("'+x.replace(/"/g,'\\\"')+'")')})}
async function init(){const keys=Object.keys(ASSETS);await Promise.all(keys.map(async k=>{const v=await call('getItem',k);if(v)memory.set(k,v)}));applyCss();window.dispatchEvent(new CustomEvent('max-assets-ready',{detail:{keys:[...memory.keys()]}}));await Promise.all(keys.map(async k=>{if(memory.has(k))return;try{const v=await fetchDataUrl(ASSETS[k]);if(v){memory.set(k,v);await call('setItem',k,v)}}catch{}}));applyCss();window.dispatchEvent(new CustomEvent('max-assets-cached',{detail:{keys:[...memory.keys()]}}))}
window.MaxAssetCache={assets:ASSETS,get:k=>memory.get(k)||'',ready:init()};
})();