/* MAXИГРА — controlled persistent image cache. Buttons are applied as data URLs before menu opens. */
(()=>{'use strict';
const ASSETS={play:'assets/кнопки/IMG_4614.jpeg',online:'assets/кнопки/IMG_4616.jpeg',profile:'assets/кнопки/IMG_4613.jpeg',leaderboard:'assets/кнопки/IMG_4609.jpeg',rules:'assets/кнопки/IMG_4612.jpeg',shop:'assets/кнопки/IMG_4605.jpeg',board_90s:'assets/boards/IMG_4486.jpeg',board_svo:'assets/boards/IMG_4487.jpeg',board_max:'assets/boards/IMG_4586.jpeg',board_orbita:'assets/boards/IMG_4587.jpeg',board_original:'assets/boards/IMG_4589.jpeg'};
const PREFIX='maxigra_asset_v1_';
const getStorage=()=>window.WebApp?.DeviceStorage;
const memory=new Map(); const IDB='maxigra-assets-v1'; let dbPromise=null;
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{try{const r=indexedDB.open(IDB,1);r.onupgradeneeded=()=>r.result.createObjectStore('assets');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}});return dbPromise}
async function idbGet(key){try{const db=await openDb();return await new Promise((resolve,reject)=>{const r=db.transaction('assets','readonly').objectStore('assets').get(key);r.onsuccess=()=>resolve(typeof r.result==='string'?r.result:'');r.onerror=()=>reject(r.error)})}catch{return ''}}
async function idbSet(key,value){try{const db=await openDb();await new Promise((resolve,reject)=>{const r=db.transaction('assets','readwrite').objectStore('assets').put(value,key);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}catch{}}
const call=(method,key,value)=>{const storage=getStorage();if(!storage?.[method])return Promise.resolve('');try{const p=value===undefined?storage[method](PREFIX+key):storage[method](PREFIX+key,value);const out=p&&typeof p.then==='function'?p.then(v=>String(v?.value??v??'')):Promise.resolve(String(p?.value??p??''));return Promise.race([out,new Promise(resolve=>setTimeout(()=>resolve(''),1500))])}catch{return Promise.resolve('')}};
async function fetchDataUrl(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('IMAGE_'+r.status);const blob=await r.blob();return await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||''));fr.onerror=reject;fr.readAsDataURL(blob)})}
async function decodeImage(src){if(!src)return false;try{const img=new Image();img.src=src;if(img.decode)await img.decode();else await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject});return true}catch{return false}}
function applyCss(){const root=document.documentElement;const map={board_90s:'--mx-img-board_90s',board_svo:'--mx-img-board_svo',board_max:'--mx-img-board_max',board_orbita:'--mx-img-board_orbita',board_original:'--mx-img-board_original'};Object.entries(map).forEach(([k,v])=>{const x=memory.get(k);if(x)root.style.setProperty(v,'url("'+x+'")')});const buttons={play:'play-btn',online:'online-play-btn',profile:'profile-btn',leaderboard:'leaderboard-btn',rules:'rules-btn',shop:'shop-btn'};Object.entries(buttons).forEach(([k,id])=>{const x=memory.get(k);const el=document.getElementById(id);if(x&&el)el.style.setProperty('--mx-btn-image','url("'+x+'")')})}
async function loadOne(k){const v=await call('getItem',k);if(v){memory.set(k,v);return true}const local=await idbGet(k);if(local){memory.set(k,local);return true}return false}
async function cacheOne(k){if(memory.has(k))return true;try{const v=await fetchDataUrl(ASSETS[k]);if(v){memory.set(k,v);applyCss();void call('setItem',k,v);void idbSet(k,v);return true}}catch{}return false}
async function ensureCritical(){const critical=['play','online','profile','leaderboard','rules','shop'];await Promise.all(critical.map(k=>loadOne(k)));applyCss();await Promise.all(critical.map(k=>cacheOne(k)));applyCss();const decoded=await Promise.all(critical.map(k=>decodeImage(memory.get(k))));return decoded.every(Boolean)}
async function init(){const criticalReady=await ensureCritical();document.documentElement.classList.add('max-buttons-ready');window.dispatchEvent(new CustomEvent('max-assets-ready',{detail:{keys:[...memory.keys()],criticalReady}}));window.dispatchEvent(new CustomEvent('max-assets-cached',{detail:{keys:[...memory.keys()],criticalReady}}));const boards=Object.keys(ASSETS).filter(k=>!['play','online','profile','leaderboard','rules','shop'].includes(k));await Promise.all(boards.map(k=>loadOne(k).then(ok=>ok||cacheOne(k))));applyCss();window.dispatchEvent(new CustomEvent('max-assets-all-cached',{detail:{keys:[...memory.keys()]}}))}
window.MaxAssetCache={assets:ASSETS,get:k=>memory.get(k)||'',apply:applyCss,ready:init()};
})();