/* Авторизация MAX. Только вход, согласие и регистрация профиля. */
(()=>{
'use strict';
const CONSENT_KEY='russian-checkers-legal-consent-v1';
const USER_KEY='russian-checkers-max-user-v1';
const readCachedUser=()=>{try{const raw=localStorage.getItem(USER_KEY);return raw?JSON.parse(raw):null}catch(e){return null}};
const cacheUser=user=>{try{localStorage.setItem(USER_KEY,JSON.stringify(user))}catch(e){}};
const goMenu=()=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('menu-screen')?.classList.add('active')};
function init(){
 if(window.__maxAuthStarted)return;window.__maxAuthStarted=true;
 const css=document.createElement('style');
 css.textContent='#max-auth-gate{position:fixed;inset:0;z-index:99999;background:#0b0e14;color:#fff;display:flex;align-items:center;justify-content:center;padding:24px;font-family:Inter,system-ui,sans-serif;text-align:center}.max-auth-card{width:min(440px,100%);padding:32px 24px;border-radius:28px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);box-shadow:0 20px 60px rgba(0,0,0,.35)}.max-auth-icon{font-size:58px;margin-bottom:16px}.max-auth-card h1{margin:0 0 10px;font-size:27px}.max-auth-card p{margin:0 auto 18px;color:rgba(255,255,255,.68);line-height:1.5}.max-auth-name{font-weight:700;margin-bottom:8px}.max-auth-loader{width:32px;height:32px;border:3px solid rgba(255,255,255,.2);border-top-color:#fff;border-radius:50%;margin:18px auto;animation:maxspin .8s linear infinite}.max-auth-retry,.max-auth-login{width:100%;padding:14px 18px;border:0;border-radius:14px;background:#fff;color:#111;font-weight:800;font-size:16px;cursor:pointer}.max-auth-retry{display:none}.max-auth-login{display:none}.max-auth-consent{display:none;text-align:left;margin:18px 0}.max-auth-consent label{display:flex;gap:10px;align-items:flex-start;color:rgba(255,255,255,.8);font-size:13px;line-height:1.45}.max-auth-consent input{width:18px;height:18px;flex:0 0 18px;margin-top:1px}.max-auth-consent a{color:#fff;text-decoration:underline}.max-auth-legal{font-size:12px!important;color:rgba(255,255,255,.5)!important;margin:12px 0 18px!important}.max-auth-error{display:none;color:#ff9b9b!important;margin-top:12px!important}@keyframes maxspin{to{transform:rotate(360deg)}}';
 document.head.appendChild(css);
 const current=window.WebApp?.initData||'';
 const cached=readCachedUser();
 if(cached&&current){window.CheckersAuth={user:cached,registered:true,ready:true,cached:true};document.body.classList.remove('max-auth-blocked');window.dispatchEvent(new CustomEvent('max-profile-ready',{detail:cached}));goMenu();fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json','x-max-init-data':current},cache:'no-store'}).then(r=>r.json().catch(()=>null)).then(d=>{if(d?.ok&&d.user){cacheUser(d.user);window.CheckersAuth={user:d.user,registered:true,ready:true};window.dispatchEvent(new CustomEvent('max-profile-ready',{detail:d.user}))}}).catch(()=>{});return;}
 document.body.classList.add('max-auth-blocked');
 const gate=document.createElement('div');gate.id='max-auth-gate';gate.innerHTML='<div class="max-auth-card"><div class="max-auth-icon">♛</div><h1>Русские шашки</h1><div class="max-auth-name" id="max-auth-name"></div><p id="max-auth-status">Войдите через MAX, чтобы начать игру.</p><div class="max-auth-consent" id="max-auth-consent"><label><input type="checkbox" id="max-auth-check"><span>Я ознакомился(лась) и принимаю <a href="privacy.html" target="_blank" rel="noopener">Политику конфиденциальности</a> и <a href="terms.html" target="_blank" rel="noopener">Пользовательское соглашение</a>.</span></label></div><p class="max-auth-legal" id="max-auth-legal">Для первого входа необходимо подтвердить согласие с документами.</p><button class="max-auth-login" id="max-auth-login">Войти через MAX</button><div class="max-auth-loader" id="max-auth-loader" style="display:none"></div><button class="max-auth-retry" id="max-auth-retry">Повторить</button><p class="max-auth-error" id="max-auth-error"></p></div>';
 document.body.appendChild(gate);
 const status=document.getElementById('max-auth-status'),loader=document.getElementById('max-auth-loader'),retry=document.getElementById('max-auth-retry'),login=document.getElementById('max-auth-login'),check=document.getElementById('max-auth-check'),consent=document.getElementById('max-auth-consent'),legal=document.getElementById('max-auth-legal'),error=document.getElementById('max-auth-error'),name=document.getElementById('max-auth-name');
 const hasConsent=()=>{try{return localStorage.getItem(CONSENT_KEY)==='1'}catch(e){return false}};
 const setMode=()=>{consent.style.display=hasConsent()?'none':'block';legal.style.display=hasConsent()?'none':'block';login.style.display='block';login.disabled=!hasConsent()&&!check.checked;login.style.opacity=login.disabled?'.5':'1';status.textContent=hasConsent()?'Войдите через MAX, чтобы продолжить.':'Перед входом ознакомьтесь с документами и подтвердите согласие.'};
 const finish=user=>{cacheUser(user);window.CheckersAuth={user,registered:true,ready:true};name.textContent=user.name||user.username||'Игрок';status.textContent='Профиль MAX подтверждён. Добро пожаловать!';loader.style.display='none';login.style.display='none';consent.style.display='none';legal.style.display='none';document.body.classList.remove('max-auth-blocked');window.dispatchEvent(new CustomEvent('max-profile-ready',{detail:user}));goMenu();setTimeout(()=>gate.remove(),350)};
 const register=async()=>{error.style.display='none';retry.style.display='none';login.style.display='none';loader.style.display='block';status.textContent='Подтверждаем вход через MAX…';const data=window.WebApp?.initData||'';if(!data){loader.style.display='none';retry.style.display='block';status.textContent='Эта игра работает только внутри MAX. Откройте мини-приложение через MAX.';return}try{const r=await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json','x-max-init-data':data},cache:'no-store'});const d=await r.json().catch(()=>({ok:false,error:'BAD_RESPONSE'}));if(!r.ok||!d.ok)throw new Error(d.error||`HTTP_${r.status}`);try{localStorage.setItem(CONSENT_KEY,'1')}catch(e){}finish(d.user)}catch(e){loader.style.display='none';login.style.display='block';login.disabled=false;login.style.opacity='1';error.textContent=e.message==='MAX_BOT_TOKEN_NOT_CONFIGURED'?'На сервере не настроен MAX_BOT_TOKEN.':e.message==='INIT_DATA_EXPIRED'?'Сеанс MAX устарел. Полностью закройте мини-приложение и откройте его снова.':'Не удалось подтвердить вход через MAX. Попробуйте ещё раз.';error.style.display='block'}};
 check.onchange=()=>{login.disabled=!check.checked;login.style.opacity=check.checked?'1':'.5'};
 login.onclick=register;
 retry.onclick=()=>{retry.style.display='none';setMode()};
 if(!current){loader.style.display='none';login.style.display='none';consent.style.display='none';legal.style.display='none';retry.style.display='block';status.textContent='Эта игра работает только внутри MAX. Откройте мини-приложение через MAX.'}else setMode();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
