(()=>{
'use strict';
let timer=null, panel=null;
const api=async()=>{const raw=window.WebApp?.initData||'';if(!raw)return null;const r=await fetch('/api/matchmaking/players',{headers:{'x-max-init-data':raw,'cache-control':'no-cache'}});if(!r.ok)return null;return r.json()};
function ensure(){if(panel)return panel;panel=document.createElement('div');panel.id='online-players-panel';panel.className='online-players-panel';panel.innerHTML='<div class="online-players-head"><span>🟢 Сейчас онлайн</span><b id="online-players-count">0</b></div><div class="online-players-sub" id="online-players-sub">Подключённых игроков пока нет</div><div class="online-players-list" id="online-players-list"></div>';document.body.appendChild(panel);return panel}
function render(data){const p=ensure(),list=p.querySelector('#online-players-list'),count=p.querySelector('#online-players-count'),sub=p.querySelector('#online-players-sub');const players=data?.players||[];count.textContent=players.length;sub.textContent=players.length?`Играют: ${data.playing||0} · ищут соперника: ${players.filter(x=>x.state==='searching').length}`:'Подключённых игроков пока нет';list.innerHTML=players.map(x=>`<div class="online-player"><div class="online-avatar">${x.me?'★':'●'}</div><div class="online-player-name">${escapeHtml(x.name)}${x.me?' <span>(вы)</span>':''}</div><div class="online-player-state ${x.state}">${x.state==='playing'?'Играет': 'Ищет игру'}</div></div>`).join('')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function refresh(){if(!window.CheckersOnline?.active)return;try{const data=await api();if(data?.ok)render(data)}catch{}}
function start(){ensure().classList.add('show');refresh();if(!timer)timer=setInterval(refresh,2000)}
function hide(){if(panel)panel.classList.remove('show');if(timer){clearInterval(timer);timer=null}}
function setup(){const style=document.createElement('style');style.textContent='.online-players-panel{position:fixed;left:12px;right:12px;bottom:12px;z-index:9998;max-width:520px;margin:auto;padding:13px 15px;border-radius:18px;background:rgba(18,22,30,.96);border:1px solid rgba(255,255,255,.1);box-shadow:0 14px 45px rgba(0,0,0,.35);color:#fff;opacity:0;pointer-events:none;transform:translateY(12px);transition:.2s}.online-players-panel.show{opacity:1;pointer-events:auto;transform:none}.online-players-head{display:flex;justify-content:space-between;align-items:center;font-weight:800}.online-players-head b{min-width:26px;text-align:center}.online-players-sub{font-size:12px;opacity:.62;margin:4px 0 8px}.online-players-list{display:flex;gap:7px;overflow-x:auto;padding-bottom:2px}.online-player{display:grid;grid-template-columns:auto 1fr;grid-template-rows:auto auto;gap:0 7px;min-width:150px;padding:8px 10px;border-radius:13px;background:rgba(255,255,255,.06)}.online-avatar{grid-row:1/3;width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.1);font-size:12px}.online-player-name{font-size:13px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.online-player-name span{font-weight:500;opacity:.55}.online-player-state{font-size:11px;opacity:.65}.online-player-state.playing{opacity:1}.game-screen.active{padding-bottom:115px}@media(max-width:480px){.online-players-panel{bottom:8px}.online-player{min-width:135px}}';document.head.appendChild(style);
const observer=new MutationObserver(()=>{if(window.CheckersOnline?.active)start();else hide()});observer.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});setInterval(()=>{if(window.CheckersOnline?.active)start()},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
