(()=>{
'use strict';
const board=document.getElementById('board'),$=id=>document.getElementById(id),core=window.CheckersOnlineCore,apiClient=window.CheckersOnlineApi;
const W=core.W,B=core.B,color=core.color,captures=core.captures,simple=core.simple;
let active=false,searching=false,polling=null,game=null,selected=null,busy=false,finishedShown=false,setupDone=false,requestInFlight=false,cancelInFlight=false,searchGeneration=0;
const api=(...args)=>apiClient.api(...args),initData=()=>apiClient.initData();
function pieces(side){const out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(game.board[r][c]&&color(game.board[r][c])===side)out.push({r,c});return out}
function hasCapture(side){return pieces(side).some(p=>captures(game.board,p.r,p.c).length)}
function legalFor(side,r,c){if(game.chain&&(game.chain.r!==r||game.chain.c!==c))return[];return game.chain||hasCapture(side)?captures(game.board,r,c):simple(game.board,r,c)}
function applyTheme(){if(!board)return;const s=window.CheckersShop?.state||{};board.dataset.board=s.selectedBoard||'default';board.dataset.pieces=s.selectedPieces||'default'}
function render(){if(!board||!game)return;applyTheme();board.innerHTML='';const possible=selected?legalFor(game.side,selected.r,selected.c):[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.type='button';cell.className='cell '+((r+c)%2?'cell-dark':'cell-light');cell.dataset.r=r;cell.dataset.c=c;if(selected?.r===r&&selected?.c===c)cell.classList.add('selected');if(possible.some(m=>m.r===r&&m.c===c))cell.classList.add('possible');if(game.lastMove&&((game.lastMove.from.r===r&&game.lastMove.from.c===c)||(game.lastMove.to.r===r&&game.lastMove.to.c===c)))cell.classList.add('last-move');const p=game.board[r][c];if(p){const piece=document.createElement('span');piece.className='piece '+(color(p)===W?'piece-white':'piece-black')+((p&4)?' piece-king':'');if(window.CheckersShop?.state?.selectedPieces==='gold')piece.classList.add('piece-gold');if(p&4)piece.textContent='♛';cell.appendChild(piece)}board.appendChild(cell)}$('white-score').textContent=pieces(W).length;$('black-score').textContent=pieces(B).length;$('turn-indicator').textContent=game.turn===game.side?'Ваш ход':'Ход соперника';$('move-count').textContent=Math.max(1,Math.floor((game.halfMoves||0)/2)+1);$('capture-info').textContent=game.chain?'⚔ Продолжайте взятие':(game.turn===game.side&&hasCapture(game.side)?'⚔ Взятие обязательно':'');$('thinking').textContent=game.turn===game.side?'':'ждём ход…';const labels=document.querySelectorAll('.game-screen .player-label');if(labels.length>=2){labels[0].firstElementChild.textContent=game.side===W?'Вы':game.opponent.name;labels[1].firstElementChild.textContent=game.side===B?'Вы':game.opponent.name}}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')}
function message(text){const el=$('online-search-text');if(el)el.textContent=text;window.dispatchEvent(new CustomEvent('online-search-message',{detail:text}))}
function stopPolling(){if(polling){clearInterval(polling);polling=null}}
function startPolling(){stopPolling();const generation=searchGeneration;polling=setInterval(()=>poll(generation),1200);poll(generation)}
function startGame(d){if(!active||cancelInFlight||!d?.game)return;game=d.game;searching=false;stopPolling();selected=null;if(game.status==='matched'||game.status==='playing'){showScreen('game-screen');render();window.dispatchEvent(new CustomEvent('online-game-started',{detail:{game}})}else if(game.status==='finished')finishOnline()}
async function poll(generation=searchGeneration){if(!active||cancelInFlight||generation!==searchGeneration||requestInFlight)return;try{const d=await api('/api/matchmaking/status');if(!active||cancelInFlight||generation!==searchGeneration)return;if(d.status==='waiting'){searching=true;message('Ждём второго игрока. Поиск идёт автоматически…');return}if(d.game)startGame(d)}catch(e){if(active&&!cancelInFlight&&generation===searchGeneration)message(e.name==='AbortError'?'Сервер отвечает дольше обычного. Продолжаем поиск…':e.message==='MAX_INIT_DATA_REQUIRED'?'Откройте игру внутри MAX — для онлайн-матча нужен профиль MAX.':e.message==='INIT_DATA_EXPIRED'?'Сессия MAX устарела. Полностью закройте мини-приложение и откройте его заново.':e.message==='INVALID_INIT_DATA'?'Не удалось подтвердить профиль MAX. Откройте игру через бота MAX ещё раз.':'Ошибка соединения. Повторяем…')}}
async function startOnline(){if(active||requestInFlight||cancelInFlight)return;if(!initData()){showScreen('online-search-screen');message('Откройте мини-приложение внутри MAX — онлайн-игра использует подтверждённый профиль MAX.');return}searchGeneration++;const generation=searchGeneration;active=true;searching=true;finishedShown=false;game=null;selected=null;cancelInFlight=false;requestInFlight=true;showScreen('online-search-screen');const b=$('online-cancel-btn');if(b){b.disabled=false;b.textContent='Отменить поиск'}message('Подключаем вас к случайному игроку MAX…');try{const d=await api('/api/matchmaking/join','POST');if(!active||cancelInFlight||generation!==searchGeneration)return;if(d.game)startGame(d);else{message('Ищем случайного соперника…');startPolling()}}catch(e){if(!active||cancelInFlight||generation!==searchGeneration)return;active=false;searching=false;stopPolling();message(e.name==='AbortError'?'Сервер не ответил вовремя. Попробуйте ещё раз.':e.message==='MAX_INIT_DATA_REQUIRED'?'Откройте мини-приложение внутри MAX — онлайн-матч нужен профиль MAX.':e.message==='INIT_DATA_EXPIRED'?'Сессия MAX устарела. Полностью закройте мини-приложение и откройте его заново.':e.message==='INVALID_INIT_DATA'?'Не удалось подтвердить профиль MAX. Откройте игру через бота MAX ещё раз.':e.message==='MAX_BOT_TOKEN_NOT_CONFIGURED'?'На сервере не настроен MAX_BOT_TOKEN.':'Не удалось начать поиск: '+e.message);if(b)b.textContent='Вернуться в меню'}finally{requestInFlight=false}}
function cancelOnline(){
 if(cancelInFlight)return;
 const wasSearching=active&&!game;
 cancelInFlight=true;
 searchGeneration++;
 active=false;
 searching=false;
 stopPolling();
 requestInFlight=false;
 game=null;
 selected=null;
 finishedShown=false;
 const b=$('online-cancel-btn');
 if(b){b.disabled=true;b.textContent='Отменяем…'}
 showScreen('menu-screen');
 // Не ждём сервер: интерфейс возвращается в меню мгновенно.
 // Старый запрос join/status уже не сможет открыть игру благодаря searchGeneration.
 if(wasSearching&&initData()){
   void api('/api/matchmaking/cancel','POST').catch(e=>console.warn('Matchmaking cancel failed',e));
 }
 // Сразу разблокируем возможность нового поиска.
 cancelInFlight=false;
}
async function move(from,to){if(busy||!game||game.status!=='playing'||game.turn!==game.side)return;busy=true;try{const d=await api('/api/matchmaking/move','POST',{roomId:game.id,from,to});game=d.game;selected=null;render();if(game.status==='finished')finishOnline()}catch(e){if(e.message!=='NOT_YOUR_TURN'&&e.message!=='BUSY')showToast(e.message==='ILLEGAL_MOVE'?'Недопустимый ход':e.message==='GAME_FINISHED'?'Партия уже завершена':'Ошибка хода')}finally{busy=false}}
function choose(r,c){if(!active||!game||game.status!=='playing'||game.turn!==game.side||busy)return;const p=game.board[r][c];if(selected){const m=legalFor(game.side,selected.r,selected.c).find(x=>x.r===r&&x.c===c);if(m){move({...selected},{r,c});return}if(!game.chain&&p&&color(p)===game.side){selected={r,c};render();return}selected=null;render();return}if(p&&color(p)===game.side&&(!hasCapture(game.side)||captures(game.board,r,c).length)){selected={r,c};render()}}
function resultText(){if(game.winner==='draw')return'🤝 Ничья';return game.winner===game.side?'🏆 Вы победили!':'⚔️ Победил соперник'}
function finishOnline(){if(finishedShown||!game||game.status!=='finished')return;finishedShown=true;stopPolling();let box=$('game-result');if(!box){box=document.createElement('div');box.id='game-result';box.className='game-result';document.body.appendChild(box)}box.innerHTML='<div class="result-card"><div class="result-title">'+resultText()+'</div><div class="result-sub">Онлайн-партия завершена</div><div class="result-actions"><button class="btn btn--primary" id="online-again">Найти нового соперника</button><button class="btn btn--secondary" id="online-menu">В меню</button></div></div>';box.classList.add('show');$('online-again').onclick=()=>{box.classList.remove('show');startOnline()};$('online-menu').onclick=()=>{box.classList.remove('show');cancelOnline()}}
async function resign(){if(!game||game.status!=='playing')return;if(!confirm('Сдаться и завершить онлайн-партию?'))return;try{const d=await api('/api/matchmaking/resign','POST',{roomId:game.id});game=d.game;render();finishOnline()}catch{showToast('Не удалось завершить партию')}}
function showToast(text){let t=$('checkers-toast');if(!t){t=document.createElement('div');t.id='checkers-toast';t.className='checkers-toast';document.body.appendChild(t)}t.textContent=text;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',1800)}
function setup(){if(setupDone)return;setupDone=true;const cancel=$('online-cancel-btn');if(cancel){cancel.onclick=e=>{e.preventDefault();e.stopPropagation();cancelOnline()};cancel.addEventListener('pointerup',e=>{e.preventDefault();e.stopPropagation();cancelOnline()},{passive:false})}document.addEventListener('click',e=>{const target=e.target?.closest?.('#online-cancel-btn');if(!target)return;e.preventDefault();e.stopImmediatePropagation();cancelOnline()},true);document.addEventListener('pointerup',e=>{const target=e.target?.closest?.('#online-cancel-btn');if(!target)return;e.preventDefault();e.stopImmediatePropagation();cancelOnline()},{capture:true,passive:false});if(board)board.addEventListener('click',e=>{const cell=e.target.closest('.cell');if(cell)choose(Number(cell.dataset.r),Number(cell.dataset.c))});const back=$('game-back');if(back)back.onclick=()=>{if(active){if(game?.status==='playing')resign();else cancelOnline()}else showScreen('menu-screen')};const newGame=$('new-game-btn');if(newGame)newGame.onclick=()=>{if(active){if(game?.status==='playing')resign();else startOnline()}else window.startGame?.()};window.CheckersOnline={get active(){return active},start:startOnline,cancel:cancelOnline};window.dispatchEvent(new CustomEvent('checkers-online-ready'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
