/* Магазин Русских шашек. Витрина и локальное состояние аккаунта. */
(()=>{
 const KEY='russian-checkers-account-v2';
 const catalog={premium:{title:'Premium',price:199,icon:'👑',tag:'ЛУЧШЕЕ',desc:'Все темы, наборы шашек и расширенные настройки.'},wood:{title:'Дерево',price:49,icon:'🪵',tag:'ДОСКА',desc:'Тёплая классическая деревянная доска.'},neon:{title:'Neon',price:79,icon:'✨',tag:'ДОСКА',desc:'Контрастная неоновая тема для ночной игры.'},marble:{title:'Мрамор',price:99,icon:'⬜',tag:'ДОСКА',desc:'Премиальная светлая мраморная доска.'},gold:{title:'Gold',price:69,icon:'🟡',tag:'ШАШКИ',desc:'Золотой набор шашек.'},master:{title:'Гроссмейстер',price:149,icon:'🏆',tag:'ИИ',desc:'Открывает максимальный уровень компьютера.'},hints:{title:'50 подсказок',price:39,icon:'💡',tag:'ПАКЕТ',desc:'50 подсказок для сложных позиций.'}};
 let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){state=null}
 state=state||{owned:[],selectedBoard:'default',selectedPieces:'default',ai:1,hints:3,coins:0,games:0,wins:0,losses:0,draws:0};
 state.owned=Array.isArray(state.owned)?state.owned:[];state.ai=Math.max(1,Math.min(4,Number(state.ai)||1));state.hints=Math.max(0,Number(state.hints)||0);state.games=Number(state.games)||0;state.wins=Number(state.wins)||0;state.losses=Number(state.losses)||0;state.draws=Number(state.draws)||0;
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}};
 const owned=id=>id==='default'||(id!=='hints'&&state.owned.includes(id))||state.owned.includes('premium');
 const buy=id=>{if(!catalog[id])return false;if(id==='hints'){state.hints+=50;if(!state.owned.includes('hints'))state.owned.push('hints');save();return true}if(state.owned.includes(id))return false;state.owned.push(id);if(id==='master')state.ai=4;save();return true};
 window.CheckersShop={catalog,state,save,owned,buy,selectBoard(id){if(owned(id)){state.selectedBoard=id;save();return true}return false},selectPieces(id){if(owned(id)){state.selectedPieces=id;save();return true}return false},setAI(n){n=Math.max(1,Math.min(4,Number(n)||1));if(n===1||owned('master')){state.ai=n;save();return true}return false},getProfile(){return {...state}}};
 save();
 function initMAXRegistration(){
   if(window.__maxRegistrationStarted)return;window.__maxRegistrationStarted=true;
   const css=document.createElement('style');css.textContent='#max-auth-gate{position:fixed;inset:0;z-index:99999;background:#0b0e14;color:#fff;display:flex;align-items:center;justify-content:center;padding:24px;font-family:Inter,system-ui,sans-serif;text-align:center}.max-auth-card{width:min(420px,100%);padding:32px 24px;border-radius:28px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);box-shadow:0 20px 60px rgba(0,0,0,.35)}.max-auth-icon{font-size:58px;margin-bottom:16px}.max-auth-card h1{margin:0 0 10px;font-size:27px}.max-auth-card p{margin:0 auto 22px;color:rgba(255,255,255,.68);line-height:1.5}.max-auth-name{font-weight:700;margin-bottom:8px}.max-auth-loader{width:32px;height:32px;border:3px solid rgba(255,255,255,.2);border-top-color:#fff;border-radius:50%;margin:18px auto;animation:maxspin .8s linear infinite}.max-auth-retry{display:none;width:100%;padding:13px 18px;border:0;border-radius:14px;background:#fff;color:#111;font-weight:700;font-size:16px}@keyframes maxspin{to{transform:rotate(360deg)}}';document.head.appendChild(css);
   const startGate=()=>{
     document.body.classList.add('max-auth-blocked');
     const gate=document.createElement('div');gate.id='max-auth-gate';gate.innerHTML='<div class="max-auth-card"><div class="max-auth-icon">♛</div><h1>Русские шашки</h1><div class="max-auth-name" id="max-auth-name"></div><p id="max-auth-status">Проверяем профиль MAX…</p><div class="max-auth-loader" id="max-auth-loader"></div><button class="max-auth-retry" id="max-auth-retry">Повторить</button></div>';document.body.appendChild(gate);
     const status=document.getElementById('max-auth-status'),loader=document.getElementById('max-auth-loader'),retry=document.getElementById('max-auth-retry'),name=document.getElementById('max-auth-name');
     const finish=user=>{window.CheckersAuth={user,registered:true,ready:true};name.textContent=user.name||user.username||'Игрок';status.textContent='Профиль MAX подтверждён. Добро пожаловать!';loader.style.display='none';document.body.classList.remove('max-auth-blocked');window.dispatchEvent(new CustomEvent('max-profile-ready',{detail:user}));setTimeout(()=>gate.remove(),350)};
     const register=async()=>{retry.style.display='none';loader.style.display='block';status.textContent='Проверяем профиль MAX…';const current=window.WebApp?.initData||'';if(!current){loader.style.display='none';retry.style.display='block';status.textContent='Эта игра работает только внутри MAX. Откройте мини-приложение через MAX.';return}try{const r=await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json','x-max-init-data':current}});const d=await r.json().catch(()=>({ok:false,error:'BAD_RESPONSE'}));if(!r.ok||!d.ok)throw new Error(d.error||`HTTP_${r.status}`);finish(d.user)}catch(e){loader.style.display='none';retry.style.display='block';status.textContent=e.message==='MAX_BOT_TOKEN_NOT_CONFIGURED'?'На сервере не настроен MAX_BOT_TOKEN.':'Не удалось подтвердить профиль MAX. Попробуйте ещё раз.'}};
     retry.onclick=register;register();
   };
   if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startGate,{once:true});else startGate();
 }
 initMAXRegistration();
 const recovery=document.createElement('script');recovery.src='ui-recovery.js?v=20260908';document.head.appendChild(recovery);
})();
